# Generated by Django 3.2.8 on 2021-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post', models.TextField()),
                ('user_id', models.BigIntegerField()),
                ('user_login', models.TextField()),
                ('post_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_login', models.TextField()),
                ('city', models.TextField()),
                ('education', models.TextField()),
                ('university', models.TextField()),
                ('sex', models.CharField(max_length=1)),
                ('born_date', models.DateField()),
                ('job', models.TextField()),
                ('job_position', models.TextField()),
                ('receipt_date', models.DateField()),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_login', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_sraff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('first_login', models.DateTimeField()),
                ('lastJoin', models.DateTimeField()),
                ('dateJoin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user_file',
            },
        ),
    ]
